#!/usr/bin/env python3
"""
MCP JIRA Server - Command-line entry point

This module allows the MCP JIRA server to be executed as a module:
    python -m mcp_jira_server

Generated by: Cursor (Claude)
"""

from .server import main

if __name__ == "__main__":
    main()