#!/usr/bin/env python3
"""MCP JIRA Server

Generated By: Cursor (Claude Sonnet 4)

A read-only Model Context Protocol server for JIRA integration.
Provides tools for searching and discovering JIRA issues and their relationships.
"""

__version__ = "0.3.0"
__author__ = "Naveen Z. Malik"