#!/usr/bin/env python3
"""Get Issue Functionality for MCP JIRA Server

Generated By: Cursor (Claude Sonnet 4)

Implements get_issue functionality for retrieving individual JIRA issues
with field selection and parent relationship consolidation.
"""

from typing import Optional
import logging

from mcp_jira_server.models import IssueDetails
from mcp_jira_server.config import make_jira_request, AuthenticationError


# Custom exception classes for get_issue functionality
class IssueNotFoundError(Exception):
    """Raised when requested issue does not exist."""
    pass


class PermissionError(Exception):
    """Raised when user lacks permission to access issue."""
    pass


class InvalidIssueKeyError(Exception):
    """Raised when issue key format is invalid."""
    pass


logger = logging.getLogger(__name__)


def get_issue(issue_key: str, fields: Optional[str] = None) -> IssueDetails:
    """Retrieve a single JIRA issue by key.

    Args:
        issue_key: JIRA issue key in PROJECT-NUMBER format (e.g., "PROJ-123")
        fields: Comma-separated list of fields to return (default: all standard fields)

    Returns:
        IssueDetails object with issue data and consolidated parent_key

    Raises:
        InvalidIssueKeyError: If issue key format is invalid
        IssueNotFoundError: If issue does not exist
        PermissionError: If user lacks permission to access issue
        AuthenticationError: If authentication fails
    """
    # Validate issue key format
    _validate_issue_key_format(issue_key)

    # Determine which fields to request
    if fields:
        # Use explicit field selection
        request_fields = fields
    else:
        # Default fields (all standard IssueDetails fields plus parent relationship fields)
        request_fields = "key,summary,status,issuetype,priority,assignee,reporter,created,updated,description,customfield_12313140,customfield_12311140"

    # Make JIRA API request
    try:
        response = make_jira_request(
            f"rest/api/2/issue/{issue_key}",
            params={
                "fields": request_fields
            }
        )

        # Handle different response status codes
        if response.status_code == 404:
            raise IssueNotFoundError("Issue not found")
        elif response.status_code == 403:
            raise PermissionError("You do not have permission to view this issue")
        elif response.status_code == 401:
            error_data = response.json()
            error_message = error_data.get("errorMessages", ["You are not authenticated"])[0]
            raise AuthenticationError(error_message)
        elif response.status_code != 200:
            raise Exception(f"Unexpected status code: {response.status_code}")

        # Parse response
        issue_data = response.json()

        # Convert JIRA issue to IssueDetails object
        return _convert_jira_issue_to_issue_details(issue_data)

    except AuthenticationError:
        # Re-raise authentication errors as-is
        raise
    except IssueNotFoundError:
        # Re-raise issue not found errors as-is
        raise
    except PermissionError:
        # Re-raise permission errors as-is
        raise
    except Exception:
        # For now, re-raise other exceptions
        raise


def _validate_issue_key_format(issue_key: str) -> None:
    """Validate JIRA issue key format (PROJECT-NUMBER).

    Args:
        issue_key: Issue key to validate

    Raises:
        InvalidIssueKeyError: If key format is invalid
    """
    import re

    if not issue_key or not isinstance(issue_key, str):
        raise InvalidIssueKeyError("Issue key must be a non-empty string")

    # JIRA issue key pattern: PROJECT-NUMBER
    # PROJECT: One or more uppercase letters
    # NUMBER: One or more digits
    pattern = r'^[A-Z]+[A-Z0-9]*-\d+$'

    if not re.match(pattern, issue_key):
        raise InvalidIssueKeyError(f"Invalid issue key format: {issue_key}. Expected format: PROJECT-NUMBER (e.g., PROJ-123)")


def _convert_jira_issue_to_issue_details(issue_data: dict) -> IssueDetails:
    """Convert JIRA API issue response to IssueDetails object.

    Args:
        issue_data: Raw JIRA issue data from API response

    Returns:
        IssueDetails object with parsed fields and consolidated parent_key
    """
    fields = issue_data.get("fields", {})

    # Extract basic fields
    key = issue_data.get("key", "")
    summary = fields.get("summary", "")

    # Extract status
    status_obj = fields.get("status", {})
    status = status_obj.get("name", "") if status_obj else ""

    # Extract issue type
    issuetype_obj = fields.get("issuetype", {})
    issue_type = issuetype_obj.get("name", "") if issuetype_obj else ""

    # Extract priority
    priority_obj = fields.get("priority", {})
    priority = priority_obj.get("name") if priority_obj else None

    # Extract assignee
    assignee_obj = fields.get("assignee", {})
    assignee = assignee_obj.get("emailAddress") if assignee_obj else None

    # Extract reporter
    reporter_obj = fields.get("reporter", {})
    reporter = reporter_obj.get("emailAddress") if reporter_obj else None

    # Extract dates
    created = fields.get("created")
    updated = fields.get("updated")

    # Extract description
    description = fields.get("description")

    # Build URL (assuming JIRA base URL pattern)
    base_url = issue_data.get("self", "").split("/rest/api/")[0] if issue_data.get("self") else ""
    url = f"{base_url}/browse/{key}" if base_url and key else ""

    # Consolidate parent relationship fields (Parent Link takes precedence over Epic Link)
    parent_key = None
    parent_link = fields.get("customfield_12311140")  # Parent Link
    epic_link = fields.get("customfield_12313140")    # Epic Link

    if parent_link:
        parent_key = parent_link
    elif epic_link:
        parent_key = epic_link

    return IssueDetails(
        key=key,
        url=url,
        summary=summary,
        type=issue_type,
        status=status,
        priority=priority,
        assignee=assignee,
        reporter=reporter,
        created=created,
        updated=updated,
        description=description,
        parent_key=parent_key,
        raw=issue_data  # Include complete JIRA response
    )