#!/usr/bin/env python3
"""Get Field Metadata Functionality for MCP JIRA Server

Generated By: Cursor (Claude Sonnet 4)

Implements get_field_metadata functionality for discovering available fields
and identifying parent relationship fields using editmeta API and caching.
"""

from typing import List, Optional
import logging

from mcp_jira_server.models import FieldMetadata
from mcp_jira_server.config import make_jira_request, AuthenticationError


# Custom exception classes for get_field_metadata functionality
class ProjectNotFoundError(Exception):
    """Raised when project does not exist."""
    pass


class SampleIssueNotFoundError(Exception):
    """Raised when sample issue does not exist."""
    pass


logger = logging.getLogger(__name__)


def get_known_parent_fields() -> List[str]:
    """Get list of all known parent field IDs across all cached projects and issue types.

    This is a convenience function for ancestor/hierarchy queries where issue types are unknown.
    Optimized for use in get_ancestors and other hierarchy traversal operations.

    Returns:
        List of unique field IDs (e.g., ["customfield_12313140", "customfield_12311140"])
        Returns empty list if no cached field metadata exists (graceful degradation)
    """
    from mcp_jira_server.config import _field_cache

    parent_field_ids = set()

    # Iterate through all cached metadata across all project::issue_type combinations
    for cached_metadata in _field_cache.values():
        for field_info in cached_metadata:
            if field_info.get('used_for_parent_key', False):
                parent_field_ids.add(field_info['id'])

    return list(parent_field_ids)


def get_field_metadata(project_key: str, sample_issue: Optional[str] = None, issue_type: Optional[str] = None) -> List[FieldMetadata]:
    """Retrieve available field metadata for a project and identify parent relationship fields.

    Args:
        project_key: JIRA project key (e.g., "PROJ", "TEST")
        sample_issue: Optional sample issue key for field discovery (e.g., "PROJ-123")
        issue_type: Optional issue type for cache-only lookup (e.g., "Story", "Bug")

    Returns:
        List of FieldMetadata objects with parent relationship field identification

    Raises:
        ProjectNotFoundError: If project does not exist
        SampleIssueNotFoundError: If sample issue does not exist
        AuthenticationError: If authentication fails
        Exception: If parameter validation fails or no cached data exists
    """
    from mcp_jira_server.config import get_cached_field_metadata, _field_cache

    # Parameter validation
    if sample_issue is not None and issue_type is not None:
        raise Exception("Cannot provide both sample_issue and issue_type parameters")

    if sample_issue is None and issue_type is None:
        raise Exception("Must provide either sample_issue or issue_type parameter")

    # Handle issue_type parameter (cache-only lookup)
    if issue_type is not None:
        cached_metadata = get_cached_field_metadata(project_key, issue_type)
        if cached_metadata:
            return _convert_cached_metadata_to_field_metadata(cached_metadata)
        else:
            raise Exception(f"No cached metadata found for {project_key}::{issue_type}")

    # Handle sample_issue parameter (API discovery)
    if sample_issue:
        # When sample_issue is provided, always do fresh API discovery
        # (cache is only used for storage, not retrieval in this mode)
        # Discovery via editmeta API first to distinguish project vs sample issue errors
        try:
            editmeta_response = make_jira_request(f"rest/api/2/issue/{sample_issue}/editmeta")

            if editmeta_response.status_code == 404:
                error_data = editmeta_response.json()
                error_messages = error_data.get("errorMessages", [])
                if any("project" in msg.lower() for msg in error_messages):
                    raise ProjectNotFoundError("Project not found")
                else:
                    raise SampleIssueNotFoundError("Sample issue not found")
            elif editmeta_response.status_code == 403:
                raise Exception("You do not have permission to access editmeta")
            elif editmeta_response.status_code != 200:
                raise Exception(f"Unexpected status code: {editmeta_response.status_code}")

            editmeta_data = editmeta_response.json()
            fields = editmeta_data.get('fields', {})

            # Get issue type to construct cache key
            issue_response = make_jira_request(
                f"rest/api/2/issue/{sample_issue}",
                params={"fields": "issuetype"}
            )

            if issue_response.status_code == 404:
                raise SampleIssueNotFoundError("Sample issue not found")
            elif issue_response.status_code == 403:
                raise Exception("You do not have permission to access this issue")
            elif issue_response.status_code != 200:
                raise Exception(f"Failed to get issue type: HTTP {issue_response.status_code}")

            issue_data = issue_response.json()
            issue_type = issue_data.get('fields', {}).get('issuetype', {}).get('name', 'Unknown')

            # Convert to FieldMetadata objects and cache
            field_metadata_list = []
            cached_metadata_list = []

            for field_id, field_info in fields.items():
                field_metadata = _convert_field_info_to_field_metadata(field_id, field_info)
                field_metadata_list.append(field_metadata)

                # Store ALL fields in cache format (not just parent fields)
                cached_metadata_list.append({
                    'id': field_id,
                    'name': field_info.get('name', 'Unknown'),
                    'schema': field_info.get('schema', {}),
                    'used_for_parent_key': field_metadata.used_for_parent_key
                })

            # Cache discovered metadata (ALL fields)
            cache_key = f"{project_key}::{issue_type}"
            _field_cache[cache_key] = cached_metadata_list

            # Return ALL fields from editmeta, not just parent fields
            return field_metadata_list

        except (ProjectNotFoundError, SampleIssueNotFoundError, AuthenticationError):
            raise
        except Exception as e:
            if "permission" in str(e).lower():
                raise e
            raise


def _convert_cached_metadata_to_field_metadata(cached_metadata: list) -> List[FieldMetadata]:
    """Convert cached metadata format to FieldMetadata objects."""
    result = []
    for cached_field in cached_metadata:
        field_id = cached_field['id']
        name = cached_field['name']
        schema = cached_field.get('schema', {})

        used_for_parent_key = cached_field.get('used_for_parent_key', False)

        field_metadata = FieldMetadata(
            id=field_id,
            name=name,
            description=None,  # Not available in cached format
            type=schema.get('type', 'unknown'),
            required=False,  # Not available in cached format
            custom=bool(schema.get('custom')),
            used_for_parent_key=used_for_parent_key
        )
        result.append(field_metadata)

    return result


def _convert_field_info_to_field_metadata(field_id: str, field_info: dict) -> FieldMetadata:
    """Convert JIRA editmeta field info to FieldMetadata object."""
    import re

    name = field_info.get('name', 'Unknown')
    schema = field_info.get('schema', {})

    # Determine if this is a parent key field using .*Link pattern
    used_for_parent_key = bool(re.search(r'.*Link', name))

    return FieldMetadata(
        id=field_id,
        name=name,
        description=None,  # JIRA editmeta doesn't provide description
        type=schema.get('type', 'unknown'),
        required=field_info.get('required', False),
        custom=bool(schema.get('custom')),
        used_for_parent_key=used_for_parent_key
    )