#!/usr/bin/env python3
"""Data Models for MCP JIRA Server

Generated By: Cursor (Claude Sonnet 4)

Data model classes based on requirements in REQUIREMENTS.md.
These models define the structure of data returned by MCP tools.
"""

from typing import List, Optional, Dict, Any
from dataclasses import dataclass
from datetime import datetime


@dataclass
class IssueDetails:
    """Issue details data model from REQUIREMENTS.md"""
    key: str                           # "PROJ-123"
    url: str                           # "https://jira.example.com/browse/PROJ-123"
    summary: str                       # "Fix authentication bug"
    type: str                          # "Story", "Bug", "Epic", "Task"
    status: str                        # "In Progress", "Done", "To Do"
    resolution: Optional[str] = None   # "Fixed", "Won't Fix", "Duplicate" (if resolved)
    priority: Optional[str] = None     # "High", "Medium", "Low" (if set)
    assignee: Optional[str] = None     # "john.doe@company.com" (current assignee)
    reporter: Optional[str] = None     # "jane.smith@company.com" (who created it)
    created: Optional[str] = None      # "2024-01-15T10:30:00Z" (ISO timestamp)
    updated: Optional[str] = None      # "2024-01-20T14:45:00Z" (ISO timestamp)
    description: Optional[str] = None  # Full issue description (markdown/text)
    acceptance_criteria: Optional[str] = None  # "User can login with SSO" (AC when available)
    parent_key: Optional[str] = None   # "PROJ-100" (immediate parent issue)
    child_keys: Optional[List[str]] = None  # ["PROJ-124", "PROJ-125"] (direct children)
    child_count: Optional[int] = None  # 5 (number of direct children)
    link_keys: Optional[List[str]] = None   # ["PROJ-200", "PROJ-300"] (linked issues)
    link_count: Optional[int] = None   # 2 (number of issue links)
    raw: Optional[Dict[str, Any]] = None  # Complete JIRA API response (optional)


@dataclass
class FieldMetadata:
    """Field metadata data model from REQUIREMENTS.md"""
    id: str                         # "customfield_12313140"
    name: str                       # "Epic Link"
    description: Optional[str] = None  # "Links this issue to its epic"
    type: str = ""                  # "epic", "user", "string", "datetime"
    required: bool = False          # true/false
    custom: bool = False            # true for custom fields
    used_for_parent_key: bool = False  # true if field name matches .*Link pattern


@dataclass
class PagedResult:
    """Paged result data model from REQUIREMENTS.md"""
    items: List[Any]        # Current page items (generic type)
    total_count: int        # Total items available
    page_size: int          # Items per page (requested)
    current_page: int       # Current page number (0-based)
    has_more: bool          # True if more pages available


