#!/usr/bin/env python3
"""Search Issues Functionality for MCP JIRA Server

Generated By: Cursor (Claude Sonnet 4)

Implements search_issues functionality with JQL detection, pagination,
and comprehensive error handling. This module follows TDD principles
with implementation guided by unit tests.
"""

from typing import Dict, Any
import logging

from mcp_jira_server.models import IssueDetails, PagedResult
from mcp_jira_server.config import make_jira_request, AuthenticationError


# Custom exception classes for search functionality
class JQLSyntaxError(Exception):
    """Raised when JQL query syntax is invalid."""
    pass


class SearchTimeoutError(Exception):
    """Raised when search request times out."""
    pass


logger = logging.getLogger(__name__)


def search_issues(query: str, max_results: int = 25, start_page: int = 0, fields: str = None) -> PagedResult:
    """Search JIRA issues using JQL queries or simple text search.

    Args:
        query: Search query (JQL or simple text)
        max_results: Maximum number of results per page (default: 25)
        start_page: Page number to return (0-based, default: 0)
        fields: Comma-separated list of fields to return (default: all standard fields)

    Returns:
        PagedResult containing IssueDetails objects and pagination metadata

    Raises:
        JQLSyntaxError: If JQL query syntax is invalid
        AuthenticationError: If authentication fails
        SearchTimeoutError: If request times out
    """

    # Detect if query is JQL or simple text
    is_jql = _is_jql_query(query)

    # Build JQL query
    if is_jql:
        jql = query
    else:
        # Escape quotes and wrap in summary search
        escaped_query = query.replace('"', '\\"')
        jql = f'summary ~ "{escaped_query}"'

    # Calculate pagination parameters
    start_at = start_page * max_results

    # Determine which fields to request
    if fields:
        # Use explicit field selection
        request_fields = fields
    else:
        # Default fields (all standard IssueDetails fields)
        request_fields = "key,summary,status,issuetype,priority,assignee,reporter,created,updated,description"

    # Make JIRA API request
    try:
        response = make_jira_request(
            "rest/api/2/search",
            params={
                "jql": jql,
                "maxResults": max_results,
                "startAt": start_at,
                "fields": request_fields
            }
        )

        # Handle different response status codes
        if response.status_code == 400:
            error_data = response.json()
            error_message = error_data.get("errorMessages", ["JQL query is invalid"])[0]
            raise JQLSyntaxError(error_message)
        elif response.status_code == 401:
            error_data = response.json()
            error_message = error_data.get("errorMessages", ["You are not authenticated"])[0]
            raise AuthenticationError(error_message)
        elif response.status_code != 200:
            raise Exception(f"Unexpected status code: {response.status_code}")

        # Parse response
        data = response.json()
        issues = data.get("issues", [])
        total = data.get("total", 0)

        # Convert JIRA issues to IssueDetails objects
        issue_details = []
        for issue in issues:
            issue_details.append(_convert_jira_issue_to_issue_details(issue))

        # Calculate pagination metadata
        has_more = (start_at + len(issues)) < total

        return PagedResult(
            items=issue_details,
            total_count=total,
            page_size=max_results,
            current_page=start_page,
            has_more=has_more
        )

    except AuthenticationError:
        # Re-raise authentication errors as-is
        raise
    except JQLSyntaxError:
        # Re-raise JQL syntax errors as-is
        raise
    except Exception as e:
        # Handle timeouts and other request exceptions
        from requests.exceptions import Timeout
        if isinstance(e, Timeout):
            raise SearchTimeoutError(str(e))
        else:
            # For now, re-raise other exceptions
            raise


def _is_jql_query(query: str) -> bool:
    """Detect if query string is JQL or simple text.

    Args:
        query: Query string to analyze

    Returns:
        True if query appears to be JQL, False for simple text
    """
    # JQL detection logic based on requirements:
    # If query contains =, AND, OR, or "order by" → treat as JQL
    jql_indicators = [
        "=",
        " and ",
        " or ",
        "order by"
    ]

    query_lower = query.lower()
    return any(indicator in query_lower for indicator in jql_indicators)


def _convert_jira_issue_to_issue_details(issue_data: Dict[str, Any]) -> IssueDetails:
    """Convert JIRA API issue response to IssueDetails object.

    Args:
        issue_data: Raw JIRA issue data from API response

    Returns:
        IssueDetails object with parsed fields
    """
    fields = issue_data.get("fields", {})

    # Extract basic fields
    key = issue_data.get("key", "")
    summary = fields.get("summary", "")

    # Extract status
    status_obj = fields.get("status", {})
    status = status_obj.get("name", "") if status_obj else ""

    # Extract issue type
    issuetype_obj = fields.get("issuetype", {})
    issue_type = issuetype_obj.get("name", "") if issuetype_obj else ""

    # Extract priority
    priority_obj = fields.get("priority", {})
    priority = priority_obj.get("name") if priority_obj else None

    # Extract assignee
    assignee_obj = fields.get("assignee", {})
    assignee = assignee_obj.get("emailAddress") if assignee_obj else None

    # Extract reporter
    reporter_obj = fields.get("reporter", {})
    reporter = reporter_obj.get("emailAddress") if reporter_obj else None

    # Extract dates
    created = fields.get("created")
    updated = fields.get("updated")

    # Extract description
    description = fields.get("description")

    # Build URL (assuming JIRA base URL pattern)
    base_url = issue_data.get("self", "").split("/rest/api/")[0] if issue_data.get("self") else ""
    url = f"{base_url}/browse/{key}" if base_url and key else ""

    return IssueDetails(
        key=key,
        url=url,
        summary=summary,
        type=issue_type,
        status=status,
        priority=priority,
        assignee=assignee,
        reporter=reporter,
        created=created,
        updated=updated,
        description=description,
        raw=issue_data  # Include complete JIRA response
    )