#!/usr/bin/env python3
"""Unit Tests for Data Models - MCP JIRA Server

Generated By: Cursor (Claude Sonnet 4)

Test the data models defined in models.py to ensure data integrity,
field validation, and proper instantiation.
"""

from .models import IssueDetails, FieldMetadata, PagedResult


class TestModelsData:
    """Test data for MODELS domain tests"""

    def setUp(self):
        """Set up test fixtures for each test method"""
        pass

    def test_models_01_issue_details_dataclass_instantiation_with_required_fields(self):
        """MODELS-01: IssueDetails dataclass instantiation with required fields"""
        # Arrange & Act - Create IssueDetails with only required fields
        issue = IssueDetails(
            key="PROJ-123",
            url="https://jira.example.com/browse/PROJ-123",
            summary="Fix authentication bug",
            type="Bug",
            status="In Progress"
        )

        # Assert - Verify required fields are set
        assert issue.key == "PROJ-123"
        assert issue.url == "https://jira.example.com/browse/PROJ-123"
        assert issue.summary == "Fix authentication bug"
        assert issue.type == "Bug"
        assert issue.status == "In Progress"

        # Assert - Verify optional fields have default values
        assert issue.resolution is None
        assert issue.priority is None
        assert issue.assignee is None
        assert issue.reporter is None
        assert issue.created is None
        assert issue.updated is None
        assert issue.description is None
        assert issue.acceptance_criteria is None
        assert issue.parent_key is None
        assert issue.child_keys is None
        assert issue.child_count is None
        assert issue.link_keys is None
        assert issue.link_count is None
        assert issue.raw is None

    def test_models_02_issue_details_dataclass_with_optional_fields_and_defaults(self):
        """MODELS-02: IssueDetails dataclass with optional fields and defaults"""
        # Arrange & Act - Create IssueDetails with all fields
        raw_data = {"id": "12345", "fields": {"description": "Full JIRA response"}}
        issue = IssueDetails(
            key="EPIC-456",
            url="https://jira.example.com/browse/EPIC-456",
            summary="User Management Epic",
            type="Epic",
            status="Done",
            resolution="Fixed",
            priority="High",
            assignee="john.doe@company.com",
            reporter="jane.smith@company.com",
            created="2024-01-15T10:30:00Z",
            updated="2024-01-20T14:45:00Z",
            description="Complete user management functionality",
            acceptance_criteria="Users can login, logout, and manage profiles",
            parent_key="INIT-100",
            child_keys=["STORY-457", "STORY-458"],
            child_count=2,
            link_keys=["BUG-789"],
            link_count=1,
            raw=raw_data
        )

        # Assert - Verify all fields are set correctly
        assert issue.key == "EPIC-456"
        assert issue.url == "https://jira.example.com/browse/EPIC-456"
        assert issue.summary == "User Management Epic"
        assert issue.type == "Epic"
        assert issue.status == "Done"
        assert issue.resolution == "Fixed"
        assert issue.priority == "High"
        assert issue.assignee == "john.doe@company.com"
        assert issue.reporter == "jane.smith@company.com"
        assert issue.created == "2024-01-15T10:30:00Z"
        assert issue.updated == "2024-01-20T14:45:00Z"
        assert issue.description == "Complete user management functionality"
        assert issue.acceptance_criteria == "Users can login, logout, and manage profiles"
        assert issue.parent_key == "INIT-100"
        assert issue.child_keys == ["STORY-457", "STORY-458"]
        assert issue.child_count == 2
        assert issue.link_keys == ["BUG-789"]
        assert issue.link_count == 1
        assert issue.raw == raw_data

    def test_models_03_field_metadata_dataclass_instantiation_with_required_fields(self):
        """MODELS-03: FieldMetadata dataclass instantiation with required fields"""
        # Arrange & Act - Create FieldMetadata with only required fields
        field = FieldMetadata(
            id="customfield_10001",
            name="Epic Link"
        )

        # Assert - Verify required fields are set
        assert field.id == "customfield_10001"
        assert field.name == "Epic Link"

        # Assert - Verify optional fields have default values
        assert field.description is None
        assert field.type == ""
        assert field.required is False
        assert field.custom is False
        assert field.used_for_parent_key is False

    def test_models_04_field_metadata_dataclass_with_optional_fields_and_defaults(self):
        """MODELS-04: FieldMetadata dataclass with optional fields and defaults"""
        # Arrange & Act - Create FieldMetadata with all fields
        field = FieldMetadata(
            id="customfield_10002",
            name="Parent Link",
            description="Links this issue to its parent",
            type="issuelink",
            required=True,
            custom=True,
            used_for_parent_key=True
        )

        # Assert - Verify all fields are set correctly
        assert field.id == "customfield_10002"
        assert field.name == "Parent Link"
        assert field.description == "Links this issue to its parent"
        assert field.type == "issuelink"
        assert field.required is True
        assert field.custom is True
        assert field.used_for_parent_key is True

    def test_models_05_paged_result_dataclass_instantiation_with_required_fields(self):
        """MODELS-05: PagedResult dataclass instantiation with required fields"""
        # Arrange & Act - Create PagedResult with only required fields (all fields are required)
        items = [
            {"key": "PROJ-123", "summary": "First issue"},
            {"key": "PROJ-124", "summary": "Second issue"}
        ]
        paged_result = PagedResult(
            items=items,
            total_count=10,
            page_size=2,
            current_page=0,
            has_more=True
        )

        # Assert - Verify all required fields are set correctly
        assert paged_result.items == items
        assert len(paged_result.items) == 2
        assert paged_result.total_count == 10
        assert paged_result.page_size == 2
        assert paged_result.current_page == 0
        assert paged_result.has_more is True

    def test_models_06_paged_result_dataclass_with_optional_fields_and_defaults(self):
        """MODELS-06: PagedResult dataclass with optional fields and defaults"""
        # Note: PagedResult currently has all required fields, but this test provides
        # consistency and a place for future optional fields to land

        # Test with different scenarios and edge cases
        # Empty result scenario
        empty_result = PagedResult(
            items=[],
            total_count=0,
            page_size=25,
            current_page=0,
            has_more=False
        )
        assert len(empty_result.items) == 0
        assert empty_result.total_count == 0
        assert empty_result.has_more is False

        # Large dataset scenario
        large_result = PagedResult(
            items=list(range(100)),  # 100 items
            total_count=10000,
            page_size=100,
            current_page=5,
            has_more=True
        )
        assert len(large_result.items) == 100
        assert large_result.total_count == 10000
        assert large_result.current_page == 5
        assert large_result.has_more is True

        # Single page scenario
        single_page = PagedResult(
            items=[{"key": "SINGLE-1"}],
            total_count=1,
            page_size=10,
            current_page=0,
            has_more=False
        )
        assert len(single_page.items) == 1
        assert single_page.total_count == 1
        assert single_page.has_more is False