#!/usr/bin/env python3
"""Unit Tests for CONFIG Domain - Configuration Management

Generated By: Cursor (Claude Sonnet 4)

Test cases CONFIG-01 through CONFIG-12 from TEST_PLAN_UNIT.md.
Tests configuration loading, validation, authentication types, and error handling.
"""

import copy
import pytest
import os
import tempfile
import yaml
from unittest.mock import patch, MagicMock
from pathlib import Path

from .test_common import (
    SAMPLE_VALID_CONFIG,
    SAMPLE_EDITMETA_RESPONSE,
    SAMPLE_ISSUE_TYPE_RESPONSE,
    create_mock_jira_response
)


class TestConfigDomain:
    """Test cases for configuration management functionality (CF1)"""

    def setup_method(self):
        """Set up test fixtures for each test method"""
        self.temp_dir = tempfile.mkdtemp()
        self.config_file = Path(self.temp_dir) / "test_config.yaml"

        # Use sample valid configuration from test_common (deep copy to avoid cross-test contamination)
        self.valid_config = copy.deepcopy(SAMPLE_VALID_CONFIG)

        # Clear module state to ensure test isolation
        import mcp_jira_server.config as config_module
        config_module._config = None
        config_module._field_cache.clear()

    def test_config_01_load_configuration_file_with_valid_yaml_structure(self):
        """CONFIG-01: Load configuration file with valid YAML structure"""
        # Arrange - Create config without environment variables
        simple_config = {
            "jira": {
                "base_url": "https://jira.example.com",
                "authentication": {
                    "type": "bearer_token",
                    "token": "fixed-test-token-12345"  # No env var substitution
                },
                "field_metadata_cache": {
                    "projects": [
                        {"project_key": "PROJ", "sample_issue": "PROJ-123"},
                        {"project_key": "TEST", "sample_issue": "TEST-456"}
                    ]
                },
                "api": {
                    "timeout_seconds": 30,
                    "max_retries": 3,
                    "retry_delay_seconds": 1
                }
            }
        }

        with open(self.config_file, 'w') as f:
            yaml.dump(simple_config, f)

        # Act & Assert - This is the TDD part - calling non-existent code
        from mcp_jira_server.config import load_config
        config = load_config(str(self.config_file))

        # Verify the loaded config matches expected structure
        assert config["jira"]["base_url"] == "https://jira.example.com"
        assert config["jira"]["authentication"]["type"] == "bearer_token"
        assert config["jira"]["authentication"]["token"] == "fixed-test-token-12345"
        assert len(config["jira"]["field_metadata_cache"]["projects"]) == 2
        assert config["jira"]["api"]["timeout_seconds"] == 30

    def test_config_02_environment_variable_substitution_with_var_name_syntax(self):
        """CONFIG-02: Environment variable substitution with ${VAR_NAME} syntax"""
        # Arrange - Create config with environment variable for testing substitution
        test_token = "test-bearer-token-12345"
        config_with_env_var = self.valid_config.copy()
        config_with_env_var["jira"]["authentication"]["token"] = "${JIRA_TOKEN}"

        with open(self.config_file, 'w') as f:
            yaml.dump(config_with_env_var, f)

        # Act & Assert - This is the TDD part - calling non-existent code
        with patch.dict(os.environ, {"JIRA_TOKEN": test_token}):
            from mcp_jira_server.config import load_config
            config = load_config(str(self.config_file))

            # Verify environment variable was substituted
            assert config["jira"]["authentication"]["token"] == test_token

    def test_config_03_support_bearer_token_authentication_type(self):
        """CONFIG-03: Support bearer_token authentication type"""
        # Arrange
        bearer_config = self.valid_config.copy()
        bearer_config["jira"]["authentication"] = {
            "type": "bearer_token",
            "token": "test-bearer-token-67890"
        }

        with open(self.config_file, 'w') as f:
            yaml.dump(bearer_config, f)

        # Act & Assert - This is the TDD part - calling non-existent validation
        from mcp_jira_server.config import load_config, get_auth_headers
        load_config(str(self.config_file))  # Load into module memory
        auth_headers = get_auth_headers()   # Uses loaded config from memory

        # Verify bearer token authentication is properly configured
        assert "Authorization" in auth_headers
        assert auth_headers["Authorization"] == "Bearer test-bearer-token-67890"

    def test_config_04_pre_cache_field_metadata_for_configured_projects_at_startup(self):
        """CONFIG-04: Pre-cache field metadata for configured projects at startup"""
        # Arrange
        with open(self.config_file, 'w') as f:
            yaml.dump(self.valid_config, f)

        # Act & Assert - This is the TDD part - following proper separation of concerns
        with patch('mcp_jira_server.get_field_metadata.make_jira_request') as mock_jira_request:
            # Mock successful field metadata discovery for both projects
            # Need different responses for editmeta and issue type calls
            def mock_request_side_effect(path, params=None):
                response_mock = MagicMock()
                response_mock.status_code = 200
                if "editmeta" in path:
                    response_mock.json.return_value = SAMPLE_EDITMETA_RESPONSE
                else:  # issue details call
                    response_mock.json.return_value = SAMPLE_ISSUE_TYPE_RESPONSE
                return response_mock
            
            mock_jira_request.side_effect = mock_request_side_effect

            # 1. Load config
            from mcp_jira_server.config import load_config
            load_config(str(self.config_file))  # Load into module memory

            # 2. Initialize cache (side effect)
            from mcp_jira_server.config import initialize_cache
            initialize_cache()  # Uses loaded config from memory

            # 3. Get metadata from cache (using known issue type from sample data)
            from mcp_jira_server.config import get_cached_field_metadata
            proj_metadata = get_cached_field_metadata("PROJ", "Feature Request")
            test_metadata = get_cached_field_metadata("TEST", "Feature Request")

            # 4. Validate response
            assert proj_metadata is not None
            assert test_metadata is not None
            assert len(proj_metadata) == 2  # Epic Link and Parent Link fields
            assert proj_metadata[0]["name"] == "Epic Link"
            assert proj_metadata[1]["name"] == "Parent Link"

            # Verify API was called for each configured project's sample issue
            assert mock_jira_request.call_count == 4  # 2 calls per project (editmeta + issue details)
            # Verify the make_jira_request calls were made correctly
            # Each call should have: rest_path as first arg (simplified signature)
            call_args_list = [call[0][0] for call in mock_jira_request.call_args_list]  # rest_path is 1st arg now
            expected_rest_paths = [
                "rest/api/2/issue/PROJ-123/editmeta",
                "rest/api/2/issue/PROJ-123",
                "rest/api/2/issue/TEST-456/editmeta",
                "rest/api/2/issue/TEST-456"
            ]
            for expected_path in expected_rest_paths:
                assert expected_path in call_args_list

    def test_config_05_handle_invalid_sample_issues_with_startup_warnings(self):
        """CONFIG-05: Handle invalid sample issues with startup warnings (don't prevent start)"""
        # Arrange - Create config with one valid and one invalid sample issue
        config_with_invalid_sample = self.valid_config.copy()
        config_with_invalid_sample["jira"]["field_metadata_cache"]["projects"] = [
            {"project_key": "PROJ", "sample_issue": "PROJ-123"},        # Valid sample
            {"project_key": "TEST", "sample_issue": "TEST-99999999"}     # Invalid sample - very high number likely doesn't exist
        ]

        with open(self.config_file, 'w') as f:
            yaml.dump(config_with_invalid_sample, f)

        # Act & Assert - This is the TDD part - testing warning behavior with proper separation
        with patch('mcp_jira_server.get_field_metadata.make_jira_request') as mock_jira_request:
            # First call (PROJ-123) succeeds, second call (TEST-99999999) fails
            def mock_request_side_effect(path, params=None):
                response_mock = MagicMock()
                if "PROJ-123" in path:
                    # Success for PROJ-123
                    response_mock.status_code = 200
                    if "editmeta" in path:
                        response_mock.json.return_value = SAMPLE_EDITMETA_RESPONSE
                    else:  # issue details call
                        response_mock.json.return_value = SAMPLE_ISSUE_TYPE_RESPONSE
                elif "TEST-99999999" in path:
                    # 404 for TEST-99999999
                    response_mock.status_code = 404
                    response_mock.json.return_value = {"errorMessages": ["Issue does not exist"]}
                return response_mock
            
            mock_jira_request.side_effect = mock_request_side_effect

            # 1. Load config
            from mcp_jira_server.config import load_config
            load_config(str(self.config_file))  # Load into module memory

            # 2. Initialize cache (should warn but not fail)
            from mcp_jira_server.config import initialize_cache
            with pytest.warns(UserWarning, match="Sample issue TEST-99999999 not found"):
                initialize_cache()  # Uses loaded config from memory

            # 3. Get metadata from cache (using known issue type from sample data)
            from mcp_jira_server.config import get_cached_field_metadata
            proj_metadata = get_cached_field_metadata("PROJ", "Feature Request")
            test_metadata = get_cached_field_metadata("TEST", "Feature Request")

            # 4. Validate response - partial cache should be available
            assert proj_metadata is not None  # Valid sample worked
            assert test_metadata is None  # Invalid sample was skipped
            assert mock_jira_request.call_count == 3  # 2 successful calls for PROJ + 1 failed for TEST

    def test_config_06_fail_startup_with_specific_error_for_missing_required_configuration(self):
        """CONFIG-06: Fail startup with specific error for missing required configuration"""
        from mcp_jira_server.config import load_config, ConfigurationError

        # Test case 1: Missing jira section entirely
        config_no_jira = {"other": "data"}
        with open(self.config_file, 'w') as f:
            yaml.dump(config_no_jira, f)
        with pytest.raises(ConfigurationError, match="Missing required configuration: jira"):
            load_config(str(self.config_file))

        # Test case 2: Missing base_url
        config_no_base_url = {
            "jira": {
                "authentication": {
                    "type": "bearer_token",
                    "token": "fixed-token"
                }
            }
        }
        with open(self.config_file, 'w') as f:
            yaml.dump(config_no_base_url, f)
        with pytest.raises(ConfigurationError, match="Missing required configuration: jira.base_url"):
            load_config(str(self.config_file))

        # Test case 3: Missing authentication section
        config_no_auth = {
            "jira": {
                "base_url": "https://jira.example.com"
            }
        }
        with open(self.config_file, 'w') as f:
            yaml.dump(config_no_auth, f)
        with pytest.raises(ConfigurationError, match="Missing required configuration: jira.authentication"):
            load_config(str(self.config_file))

        # Test case 4: Missing authentication type
        config_no_auth_type = {
            "jira": {
                "base_url": "https://jira.example.com",
                "authentication": {
                    "token": "fixed-token"
                }
            }
        }
        with open(self.config_file, 'w') as f:
            yaml.dump(config_no_auth_type, f)
        with pytest.raises(ConfigurationError, match="Missing required configuration: jira.authentication.type"):
            load_config(str(self.config_file))

        # Test case 5: Unsupported authentication type
        config_bad_auth_type = {
            "jira": {
                "base_url": "https://jira.example.com",
                "authentication": {
                    "type": "unsupported_auth",
                    "token": "fixed-token"
                }
            }
        }
        with open(self.config_file, 'w') as f:
            yaml.dump(config_bad_auth_type, f)
        with pytest.raises(ConfigurationError, match="Unsupported authentication type: unsupported_auth"):
            load_config(str(self.config_file))

        # Test case 6: Missing token
        config_no_token = {
            "jira": {
                "base_url": "https://jira.example.com",
                "authentication": {
                    "type": "bearer_token"
                }
            }
        }
        with open(self.config_file, 'w') as f:
            yaml.dump(config_no_token, f)
        with pytest.raises(ConfigurationError, match="Missing required configuration: jira.authentication.token"):
            load_config(str(self.config_file))

    def test_config_07_fail_startup_with_connectivity_error_for_invalid_jira_base_url(self):
        """CONFIG-07: Fail startup with connectivity error for invalid JIRA base URL"""
        # Arrange
        invalid_url_config = self.valid_config.copy()
        invalid_url_config["jira"]["base_url"] = "https://invalid-jira-url.example.com"

        with open(self.config_file, 'w') as f:
            yaml.dump(invalid_url_config, f)

        # Act & Assert - This is the TDD part - testing connectivity validation during startup
        with patch('mcp_jira_server.config.requests.get') as mock_get:
            from requests.exceptions import ConnectionError as RequestsConnectionError
            mock_get.side_effect = RequestsConnectionError("Connection refused")

            from mcp_jira_server.config import load_config, validate_jira_connection
            load_config(str(self.config_file))  # Load into module memory
            with pytest.raises(ConnectionError, match="Failed to connect to JIRA"):
                validate_jira_connection()  # Uses loaded config from memory

    def test_config_08_fail_startup_with_auth_error_for_authentication_failure(self):
        """CONFIG-08: Fail startup with auth error for authentication failure"""
        # Arrange
        with open(self.config_file, 'w') as f:
            yaml.dump(self.valid_config, f)

        # Act & Assert - This is the TDD part - testing auth validation during startup
        with patch('mcp_jira_server.config.make_jira_request') as mock_jira_request:
            mock_jira_request.return_value = create_mock_jira_response(401, error_messages=["Authentication failed"])

            from mcp_jira_server.config import load_config, validate_jira_connection, AuthenticationError
            load_config(str(self.config_file))  # Load into module memory
            with pytest.raises(AuthenticationError, match="Authentication failed"):
                validate_jira_connection()  # Uses loaded config from memory

    def test_config_09_fail_startup_with_parsing_error_for_malformed_yaml(self):
        """CONFIG-09: Fail startup with parsing error for malformed YAML"""
        # Arrange - Create malformed YAML (key without value)
        malformed_yaml = """
        jira:
        base_url: "https://jira.example.com"
        authentication:
            type: "bearer_token"
            token: "test-token-for-malformed-yaml"
        field_metadata_cache:
            projects:
            - project_key: "PROJ"
                sample_issue: "PROJ-123"
            - project_key: "TEST"
                sample_issue: "TEST-456"
        api:
            timeout_seconds: 30
            max_retries: 3
            retry_delay_seconds:
            # Key without value above - invalid YAML
        """

        with open(self.config_file, 'w') as f:
            f.write(malformed_yaml)

        # Act & Assert - This is the TDD part - testing YAML parsing error handling
        from mcp_jira_server.config import load_config
        with pytest.raises(yaml.YAMLError, match="Error parsing configuration file"):
            load_config(str(self.config_file))

    def test_config_10_never_log_or_expose_authentication_credentials(self):
        """CONFIG-10: Never log or expose authentication credentials"""
        # Arrange
        sensitive_token = "super-secret-token-12345"

        with open(self.config_file, 'w') as f:
            yaml.dump(self.valid_config, f)

        # Act & Assert - This is the TDD part - testing that credentials are never logged
        with patch.dict(os.environ, {"JIRA_TOKEN": sensitive_token}):
            with patch('mcp_jira_server.config.logging') as mock_logging:
                from mcp_jira_server.config import load_config
                load_config(str(self.config_file))  # Load into module memory

                # Verify no log calls contain the sensitive token
                for call in mock_logging.debug.call_args_list:
                    assert sensitive_token not in str(call)
                for call in mock_logging.info.call_args_list:
                    assert sensitive_token not in str(call)
                for call in mock_logging.warning.call_args_list:
                    assert sensitive_token not in str(call)
                for call in mock_logging.error.call_args_list:
                    assert sensitive_token not in str(call)

    def test_config_11_test_make_jira_request_error_handling(self):
        """CONFIG-11: Test make_jira_request error handling when config not loaded"""
        from mcp_jira_server.config import make_jira_request, ConfigurationError

        # Reset module state to simulate config not loaded
        import mcp_jira_server.config as config_module
        config_module._config = None

        # Should raise ConfigurationError when config not loaded
        with pytest.raises(ConfigurationError, match="Configuration not loaded"):
            make_jira_request("rest/api/2/serverInfo")

    def test_config_11b_test_make_jira_request_success_path(self):
        """CONFIG-11b: Test make_jira_request successful execution with valid config"""
        # Setup valid config
        with open(self.config_file, 'w') as f:
            yaml.dump(self.valid_config, f)

        from mcp_jira_server.config import load_config, make_jira_request
        from unittest.mock import Mock

        # Load config first
        load_config(self.config_file)

        # Mock requests.get at the module level
        with patch('mcp_jira_server.config.requests.get') as mock_get:
            mock_response = Mock()
            mock_response.status_code = 200
            mock_response.json.return_value = {"version": "8.5.0"}
            mock_get.return_value = mock_response

            # Call make_jira_request - this should execute the real function
            result = make_jira_request("rest/api/2/serverInfo")

            # Verify the function constructed the URL and headers correctly
            expected_url = "https://jira.example.com/rest/api/2/serverInfo"
            expected_headers = {
                "Authorization": "Bearer fixed-test-token-12345",
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
            
            mock_get.assert_called_once_with(
                expected_url,
                headers=expected_headers,
                params=None,
                timeout=30
            )
            
            # Verify we got the response back
            assert result == mock_response

    def test_config_11c_test_make_jira_request_connection_error(self):
        """CONFIG-11c: Test make_jira_request handling ConnectionError"""
        # Setup valid config
        with open(self.config_file, 'w') as f:
            yaml.dump(self.valid_config, f)

        from mcp_jira_server.config import load_config, make_jira_request
        from requests.exceptions import ConnectionError as RequestsConnectionError

        # Load config first
        load_config(self.config_file)

        # Mock requests.get to raise ConnectionError
        with patch('mcp_jira_server.config.requests.get') as mock_get:
            mock_get.side_effect = RequestsConnectionError("Connection refused")

            # Should raise ConnectionError with our custom message
            with pytest.raises(ConnectionError, match="Failed to connect to JIRA"):
                make_jira_request("rest/api/2/serverInfo")

    def test_config_11d_test_make_jira_request_general_exception(self):
        """CONFIG-11d: Test make_jira_request handling general RequestException"""
        # Setup valid config
        with open(self.config_file, 'w') as f:
            yaml.dump(self.valid_config, f)

        from mcp_jira_server.config import load_config, make_jira_request
        from requests.exceptions import RequestException

        # Load config first
        load_config(self.config_file)

        # Mock requests.get to raise RequestException
        with patch('mcp_jira_server.config.requests.get') as mock_get:
            mock_get.side_effect = RequestException("Timeout occurred")

            # Should re-raise the original RequestException
            with pytest.raises(RequestException, match="Timeout occurred"):
                make_jira_request("rest/api/2/serverInfo")

    def test_config_12_test_cache_miss_scenarios(self):
        """CONFIG-12: Test cache miss scenarios in get_cached_field_metadata"""
        # Load valid config first
        with open(self.config_file, 'w') as f:
            yaml.dump(self.valid_config, f)

        from mcp_jira_server.config import load_config, get_cached_field_metadata
        load_config(str(self.config_file))

        # Test cache miss for unknown project/issue type combination
        result = get_cached_field_metadata("UNKNOWN", "Story")
        assert result is None

        result = get_cached_field_metadata("PROJ", "UnknownType")
        assert result is None

    def test_config_13_test_environment_variable_substitution_edge_cases(self):
        """CONFIG-13: Test environment variable substitution edge cases"""
        # Test recursive substitution (when value is not a string)
        from mcp_jira_server.config import _substitute_env_vars_recursive

        # Test with non-string value (should return as-is)
        result = _substitute_env_vars_recursive(123)
        assert result == 123

        result = _substitute_env_vars_recursive(None)
        assert result is None

        result = _substitute_env_vars_recursive(True)
        assert result is True

        # Test with list and dict structures
        test_list = ["${JIRA_TOKEN}", "static_value"]
        test_dict = {"token": "${JIRA_TOKEN}", "url": "static"}

        with patch.dict(os.environ, {"JIRA_TOKEN": "test-token"}):
            result_list = _substitute_env_vars_recursive(test_list)
            assert result_list == ["test-token", "static_value"]

            result_dict = _substitute_env_vars_recursive(test_dict)
            assert result_dict == {"token": "test-token", "url": "static"}

    def test_config_14_test_request_exception_handling_in_initialize_cache(self):
        """CONFIG-14: Test request exception handling in initialize_cache"""
        # Setup valid config
        with open(self.config_file, 'w') as f:
            yaml.dump(self.valid_config, f)

        from requests.exceptions import RequestException
        with patch('mcp_jira_server.get_field_metadata.make_jira_request') as mock_jira_request:
            # Mock RequestException (non-critical error that should be logged and continue)
            mock_jira_request.side_effect = RequestException("Network error")

            from mcp_jira_server.config import load_config, initialize_cache
            load_config(str(self.config_file))

            # Should not raise exception, just log warnings
            initialize_cache()

    def test_config_15_environment_variable_substitution_with_non_string_values_and_missing_variables(self):
        """CONFIG-15: Test environment variable substitution with non-string values and missing variables"""
        from mcp_jira_server.config import _substitute_env_vars, ConfigurationError
        
        # Test with non-string input (should return as-is)
        non_string_values = [123, None, ['list'], {'dict': 'value'}]
        for value in non_string_values:
            result = _substitute_env_vars(value)
            assert result == value, f"Non-string value {value} should be returned unchanged"
        
        # Test with missing environment variable
        with pytest.raises(ConfigurationError, match="Environment variable NONEXISTENT_VAR not found"):
            _substitute_env_vars("${NONEXISTENT_VAR}")

    def test_config_16_configuration_file_loading_with_missing_files_and_empty_content(self):
        """CONFIG-16: Test configuration file loading with missing files and empty content"""
        from mcp_jira_server.config import load_config, ConfigurationError
        
        # Test with non-existent file
        nonexistent_file = Path(self.temp_dir) / "nonexistent.yaml"
        with pytest.raises(ConfigurationError, match="Configuration file not found"):
            load_config(str(nonexistent_file))
        
        # Test with empty file
        empty_config_file = Path(self.temp_dir) / "empty.yaml"
        empty_config_file.write_text("")
        with pytest.raises(ConfigurationError, match="Configuration file is empty"):
            load_config(str(empty_config_file))

    def test_config_17_authentication_header_generation_error_scenarios(self):
        """CONFIG-17: Test authentication header generation error scenarios"""
        from mcp_jira_server.config import get_auth_headers, ConfigurationError, AuthenticationError
        
        # Test without loaded config
        # First clear any existing config
        import mcp_jira_server.config as config_module
        config_module._config = None
        
        with pytest.raises(ConfigurationError, match="Configuration not loaded"):
            get_auth_headers()
        
        # Test with invalid auth type by modifying config after loading
        with open(self.config_file, 'w') as f:
            yaml.dump(self.valid_config, f)
        
        from mcp_jira_server.config import load_config
        load_config(str(self.config_file))
        
        # Directly modify the loaded config to test unsupported auth type
        config_module._config['jira']['authentication']['type'] = 'unsupported_auth'
        
        with pytest.raises(AuthenticationError, match="Unsupported authentication type"):
            get_auth_headers()

    def test_config_18_field_metadata_caching_with_unloaded_config_and_api_errors(self):
        """CONFIG-18: Test field metadata caching with unloaded config and API errors"""
        from mcp_jira_server.config import initialize_cache, ConfigurationError
        from unittest.mock import patch
        
        # Test without loaded config
        # First clear any existing config
        import mcp_jira_server.config as config_module
        config_module._config = None
        
        with pytest.raises(ConfigurationError, match="Configuration not loaded"):
            initialize_cache()
        
        # Test with API errors (HTTP 404 and other errors)
        with open(self.config_file, 'w') as f:
            yaml.dump(self.valid_config, f)
        
        from mcp_jira_server.config import load_config
        load_config(str(self.config_file))
        
        with patch('mcp_jira_server.get_field_metadata.make_jira_request') as mock_jira_request:
            # Mock 404 response for editmeta (should warn and continue)
            mock_404_response = create_mock_jira_response(404)
            # Mock 500 error for editmeta (should warn and continue)
            mock_500_response = create_mock_jira_response(500)
            
            mock_jira_request.side_effect = [mock_404_response, mock_500_response]
            
            # Should not raise exception, just log warnings
            initialize_cache()

    def teardown_method(self):
        """Clean up test fixtures after each test method"""
        import shutil
        if Path(self.temp_dir).exists():
            shutil.rmtree(self.temp_dir)