#!/usr/bin/env python3
"""Unit Tests for CONFIG Domain - Configuration Management

Generated By: Cursor (Claude Sonnet 4)

Test cases CONFIG-01 through CONFIG-12 from TEST_PLAN_UNIT.md.
Tests configuration loading, validation, authentication types, and error handling.
"""

import pytest
import os
import tempfile
import yaml
from unittest.mock import Mock, patch
from pathlib import Path

from .test_common import (
    SAMPLE_VALID_CONFIG,
    SAMPLE_FIELD_METADATA_RESPONSE,
    create_mock_jira_response
)


class TestConfigDomain:
    """Test cases for configuration management functionality (CF1)"""
    
    def setup_method(self):
        """Set up test fixtures for each test method"""
        self.temp_dir = tempfile.mkdtemp()
        self.config_file = Path(self.temp_dir) / "test_config.yaml"
        
        # Use sample valid configuration from test_common
        self.valid_config = SAMPLE_VALID_CONFIG
    
    def test_config_01_load_configuration_file_with_valid_yaml_structure(self):
        """CONFIG-01: Load configuration file with valid YAML structure"""
        # Arrange
        with open(self.config_file, 'w') as f:
            yaml.dump(self.valid_config, f)
        
        # Act & Assert - This is the TDD part - calling non-existent code
        from mcp_jira_server.config import load_config
        config = load_config(str(self.config_file))
        
        # Verify the loaded config matches expected structure
        assert config["jira"]["base_url"] == "https://jira.example.com"
        assert config["jira"]["authentication"]["type"] == "bearer_token"
        assert config["jira"]["authentication"]["token"] == "${JIRA_TOKEN}"
        assert len(config["jira"]["field_metadata_cache"]["projects"]) == 2
        assert config["jira"]["api"]["timeout_seconds"] == 30

    def test_config_02_environment_variable_substitution_with_var_name_syntax(self):
        """CONFIG-02: Environment variable substitution with ${VAR_NAME} syntax"""
        # Arrange
        test_token = "test-bearer-token-12345"
        config_with_env_var = self.valid_config.copy()
        
        with open(self.config_file, 'w') as f:
            yaml.dump(config_with_env_var, f)
        
        # Act & Assert - This is the TDD part - calling non-existent code
        with patch.dict(os.environ, {"JIRA_TOKEN": test_token}):
            from mcp_jira_server.config import load_config
            config = load_config(str(self.config_file))
            
            # Verify environment variable was substituted
            assert config["jira"]["authentication"]["token"] == test_token

    def test_config_03_support_bearer_token_authentication_type(self):
        """CONFIG-03: Support bearer_token authentication type"""
        # Arrange
        bearer_config = self.valid_config.copy()
        bearer_config["jira"]["authentication"] = {
            "type": "bearer_token",
            "token": "${JIRA_TOKEN}"
        }
        
        with open(self.config_file, 'w') as f:
            yaml.dump(bearer_config, f)
        
        # Act & Assert - This is the TDD part - calling non-existent validation
        with patch.dict(os.environ, {"JIRA_TOKEN": "test-token"}):
            from mcp_jira_server.config import load_config, get_auth_headers
            load_config(str(self.config_file))  # Load into module memory
            auth_headers = get_auth_headers()   # Uses loaded config from memory
            
            # Verify bearer token authentication is properly configured
            assert "Authorization" in auth_headers
            assert auth_headers["Authorization"] == "Bearer test-token"

    def test_config_04_pre_cache_field_metadata_for_configured_projects_at_startup(self):
        """CONFIG-04: Pre-cache field metadata for configured projects at startup"""
        # Arrange
        with open(self.config_file, 'w') as f:
            yaml.dump(self.valid_config, f)
        
        # Act & Assert - This is the TDD part - following proper separation of concerns
        with patch('mcp_jira_server.config.requests.get') as mock_get:
            # Mock successful field metadata discovery for both projects
            mock_get.return_value = create_mock_jira_response(200, SAMPLE_FIELD_METADATA_RESPONSE)
            
            # 1. Load config
            from mcp_jira_server.config import load_config
            load_config(str(self.config_file))  # Load into module memory
            
            # 2. Initialize cache (side effect)
            from mcp_jira_server.config import initialize_cache
            initialize_cache()  # Uses loaded config from memory
            
            # 3. Get metadata from cache
            from mcp_jira_server.config import get_cached_field_metadata
            proj_metadata = get_cached_field_metadata("PROJ")
            test_metadata = get_cached_field_metadata("TEST")
            
            # 4. Validate response
            assert proj_metadata is not None
            assert test_metadata is not None
            assert len(proj_metadata) == 2  # Epic Link and Parent Link fields
            assert proj_metadata[0]["name"] == "Epic Link"
            assert proj_metadata[1]["name"] == "Parent Link"
            
            # Verify API was called for each configured project's sample issue
            assert mock_get.call_count == 2
            # Note: URLs will be determined by the loaded config in memory
            expected_base_url = "https://jira.example.com"  # Matches SAMPLE_VALID_CONFIG
            mock_get.assert_any_call(f"{expected_base_url}/rest/api/2/issue/PROJ-123/editmeta")
            mock_get.assert_any_call(f"{expected_base_url}/rest/api/2/issue/TEST-456/editmeta")

    def test_config_05_handle_invalid_sample_issues_with_startup_warnings(self):
        """CONFIG-05: Handle invalid sample issues with startup warnings (don't prevent start)"""
        # Arrange - Create config with one valid and one invalid sample issue
        config_with_invalid_sample = self.valid_config.copy()
        config_with_invalid_sample["jira"]["field_metadata_cache"]["projects"] = [
            {"project_key": "PROJ", "sample_issue": "PROJ-123"},        # Valid sample
            {"project_key": "TEST", "sample_issue": "TEST-99999999"}     # Invalid sample - very high number likely doesn't exist
        ]
        
        with open(self.config_file, 'w') as f:
            yaml.dump(config_with_invalid_sample, f)
        
        # Act & Assert - This is the TDD part - testing warning behavior with proper separation
        with patch('mcp_jira_server.config.requests.get') as mock_get:
            # First call (PROJ-123) succeeds, second call (TEST-99999999) fails 
            mock_get.side_effect = [
                create_mock_jira_response(200, SAMPLE_FIELD_METADATA_RESPONSE),
                create_mock_jira_response(404, error_messages=["Issue does not exist"])
            ]
            
            # 1. Load config
            from mcp_jira_server.config import load_config
            load_config(str(self.config_file))  # Load into module memory
            
            # 2. Initialize cache (should warn but not fail)
            from mcp_jira_server.config import initialize_cache
            with pytest.warns(UserWarning, match="Sample issue TEST-99999999 not found"):
                initialize_cache()  # Uses loaded config from memory
            
            # 3. Get metadata from cache
            from mcp_jira_server.config import get_cached_field_metadata
            proj_metadata = get_cached_field_metadata("PROJ")
            test_metadata = get_cached_field_metadata("TEST")
            
            # 4. Validate response - partial cache should be available
            assert proj_metadata is not None  # Valid sample worked
            assert test_metadata is None  # Invalid sample was skipped
            assert mock_get.call_count == 2

    def test_config_06_fail_startup_with_specific_error_for_missing_required_configuration(self):
        """CONFIG-06: Fail startup with specific error for missing required configuration"""
        # Arrange - Create config missing required base_url
        invalid_config = {
            "jira": {
                "authentication": {
                    "type": "bearer_token",
                    "token": "${JIRA_TOKEN}"
                }
                # Missing required base_url
            }
        }
        
        with open(self.config_file, 'w') as f:
            yaml.dump(invalid_config, f)
        
        # Act & Assert - This is the TDD part - expecting specific exception
        from mcp_jira_server.config import load_config, ConfigurationError
        with pytest.raises(ConfigurationError, match="Missing required configuration: jira.base_url"):
            load_config(str(self.config_file))

    def test_config_07_fail_startup_with_connectivity_error_for_invalid_jira_base_url(self):
        """CONFIG-07: Fail startup with connectivity error for invalid JIRA base URL"""
        # Arrange
        invalid_url_config = self.valid_config.copy()
        invalid_url_config["jira"]["base_url"] = "https://invalid-jira-url.example.com"
        
        with open(self.config_file, 'w') as f:
            yaml.dump(invalid_url_config, f)
        
        # Act & Assert - This is the TDD part - testing connectivity validation during startup
        with patch('mcp_jira_server.config.requests.get') as mock_get:
            from requests.exceptions import ConnectionError
            mock_get.side_effect = ConnectionError("Connection failed")
            
            from mcp_jira_server.config import load_config, validate_jira_connection
            load_config(str(self.config_file))  # Load into module memory
            with pytest.raises(ConnectionError, match="Failed to connect to JIRA"):
                validate_jira_connection()  # Uses loaded config from memory

    def test_config_08_fail_startup_with_auth_error_for_authentication_failure(self):
        """CONFIG-08: Fail startup with auth error for authentication failure"""
        # Arrange
        with open(self.config_file, 'w') as f:
            yaml.dump(self.valid_config, f)
        
        # Act & Assert - This is the TDD part - testing auth validation during startup
        with patch('mcp_jira_server.config.requests.get') as mock_get:
            mock_get.return_value = create_mock_jira_response(401, error_messages=["Authentication failed"])
            
            from mcp_jira_server.config import load_config, validate_jira_connection, AuthenticationError
            load_config(str(self.config_file))  # Load into module memory
            with pytest.raises(AuthenticationError, match="Authentication failed"):
                validate_jira_connection()  # Uses loaded config from memory

    def test_config_09_fail_startup_with_parsing_error_for_malformed_yaml(self):
        """CONFIG-09: Fail startup with parsing error for malformed YAML"""
        # Arrange - Create malformed YAML (key without value)
        malformed_yaml = """
        jira:
        base_url: "https://jira.example.com"
        authentication:
            type: "bearer_token"
            token: "${JIRA_TOKEN}"
        field_metadata_cache:
            projects:
            - project_key: "PROJ"
                sample_issue: "PROJ-123"
            - project_key: "TEST" 
                sample_issue: "TEST-456"
        api:
            timeout_seconds: 30
            max_retries: 3
            retry_delay_seconds:
            # Key without value above - invalid YAML
        """
        
        with open(self.config_file, 'w') as f:
            f.write(malformed_yaml)
        
        # Act & Assert - This is the TDD part - testing YAML parsing error handling
        from mcp_jira_server.config import load_config
        with pytest.raises(yaml.YAMLError, match="Error parsing configuration file"):
            load_config(str(self.config_file))

    def test_config_10_never_log_or_expose_authentication_credentials(self):
        """CONFIG-10: Never log or expose authentication credentials"""
        # Arrange
        sensitive_token = "super-secret-token-12345"
        
        with open(self.config_file, 'w') as f:
            yaml.dump(self.valid_config, f)
        
        # Act & Assert - This is the TDD part - testing that credentials are never logged
        with patch.dict(os.environ, {"JIRA_TOKEN": sensitive_token}):
            with patch('mcp_jira_server.config.logging') as mock_logging:
                from mcp_jira_server.config import load_config
                load_config(str(self.config_file))  # Load into module memory
                
                # Verify no log calls contain the sensitive token
                for call in mock_logging.debug.call_args_list:
                    assert sensitive_token not in str(call)
                for call in mock_logging.info.call_args_list:
                    assert sensitive_token not in str(call)
                for call in mock_logging.warning.call_args_list:
                    assert sensitive_token not in str(call)
                for call in mock_logging.error.call_args_list:
                    assert sensitive_token not in str(call)

    def teardown_method(self):
        """Clean up test fixtures after each test method"""
        import shutil
        if Path(self.temp_dir).exists():
            shutil.rmtree(self.temp_dir)