#!/usr/bin/env python3
"""Unit Tests for Search Issues Functionality

Generated By: Cursor (Claude Sonnet 4)

Unit tests for search_issues functionality based on TEST_PLAN_UNIT.md.
Tests are organized to match the test plan structure: basic functionality,
pagination, and error handling.
"""

import unittest
import pytest
from unittest.mock import patch
from pathlib import Path
import tempfile
import yaml
from typing import List, Dict, Any

from mcp_jira_server.models import PagedResult


class TestSearchIssues(unittest.TestCase):
    """Test class for search_issues functionality following TEST_PLAN_UNIT.md"""

    def setUp(self):
        """Set up test fixtures before each test method"""
        # Create temporary directory and config for testing
        self.temp_dir = tempfile.mkdtemp()
        self.config_file = Path(self.temp_dir) / "test_config.yaml"

        # Standard test configuration
        self.valid_config = {
            "jira": {
                "base_url": "https://test-jira.example.com",
                "authentication": {
                    "type": "bearer_token",
                    "token": "test_token_123"
                },
                "projects": {
                    "TEST": {
                        "sample_issues": ["TEST-123"]
                    }
                }
            }
        }

    def create_mock_jira_response(self, issues: List[Dict[str, Any]], total: int = None) -> Dict[str, Any]:
        """Helper to create mock JIRA search API responses"""
        if total is None:
            total = len(issues)

        return {
            "issues": issues,
            "total": total,
            "startAt": 0,
            "maxResults": 25,
            "isLast": len(issues) < 25
        }

    def create_mock_issue_data(self, key: str, summary: str, status: str = "Open") -> Dict[str, Any]:
        """Helper to create mock JIRA issue data"""
        return {
            "key": key,
            "self": f"https://test-jira.example.com/rest/api/2/issue/{key}",
            "fields": {
                "summary": summary,
                "status": {"name": status},
                "issuetype": {"name": "Story"},
                "priority": {"name": "Medium"},
                "assignee": {
                    "emailAddress": "test@example.com",
                    "displayName": "Test User"
                },
                "reporter": {
                    "emailAddress": "reporter@example.com",
                    "displayName": "Reporter User"
                },
                "created": "2024-01-15T10:30:00.000Z",
                "updated": "2024-01-20T14:45:00.000Z",
                "description": "Test description"
            }
        }

    def tearDown(self):
        """Clean up test fixtures after each test method"""
        import shutil
        if Path(self.temp_dir).exists():
            shutil.rmtree(self.temp_dir)

    # Basic Functionality Tests (SEARCH-01 to SEARCH-05)

    def test_search_01_simple_text_query_searches_issue_summaries(self):
        """SEARCH-01: Simple text query searches issue summaries"""
        # Arrange
        with open(self.config_file, 'w') as f:
            yaml.dump(self.valid_config, f)

        mock_issues = [
            self.create_mock_issue_data("TEST-123", "Fix authentication bug"),
            self.create_mock_issue_data("TEST-124", "Add user dashboard")
        ]
        mock_response = self.create_mock_jira_response(mock_issues, total=2)

        with patch('mcp_jira_server.search.make_jira_request') as mock_request:
            mock_request.return_value.status_code = 200
            mock_request.return_value.json.return_value = mock_response

            from mcp_jira_server.config import load_config
            from mcp_jira_server.search import search_issues

            load_config(str(self.config_file))

            # Act
            result = search_issues("authentication", max_results=25, start_page=0)

            # Assert
            assert isinstance(result, PagedResult)
            assert len(result.items) == 2
            assert result.total_count == 2
            assert result.has_more is False
            assert result.current_page == 0

            # Verify JQL was constructed for simple text search
            mock_request.assert_called_once()
            args, kwargs = mock_request.call_args
            assert "rest/api/2/search" in args[0]
            assert "summary ~ \"authentication\"" in kwargs["params"]["jql"]
            # Verify default fields are used
            assert "key,summary,status,issuetype,priority,assignee,reporter,created,updated,description" in kwargs["params"]["fields"]

    def test_search_02_jql_detection_with_equals_sign(self):
        """SEARCH-02: JQL detection with equals sign (=)"""
        # Arrange
        with open(self.config_file, 'w') as f:
            yaml.dump(self.valid_config, f)

        mock_response = self.create_mock_jira_response([], total=0)

        with patch('mcp_jira_server.search.make_jira_request') as mock_request:
            mock_request.return_value.status_code = 200
            mock_request.return_value.json.return_value = mock_response

            from mcp_jira_server.config import load_config
            from mcp_jira_server.search import search_issues

            load_config(str(self.config_file))

            # Act
            search_issues("project = TEST", max_results=25, start_page=0)

            # Assert
            mock_request.assert_called_once()
            args, kwargs = mock_request.call_args
            # Should use the query directly as JQL (not wrap in summary search)
            assert kwargs["params"]["jql"] == "project = TEST"

    def test_search_03_jql_detection_with_and_operator(self):
        """SEARCH-03: JQL detection with AND operator"""
        # Arrange
        with open(self.config_file, 'w') as f:
            yaml.dump(self.valid_config, f)

        mock_response = self.create_mock_jira_response([], total=0)

        with patch('mcp_jira_server.search.make_jira_request') as mock_request:
            mock_request.return_value.status_code = 200
            mock_request.return_value.json.return_value = mock_response

            from mcp_jira_server.config import load_config
            from mcp_jira_server.search import search_issues

            load_config(str(self.config_file))

            # Act
            search_issues("status = Open AND assignee = currentUser()", max_results=25, start_page=0)

            # Assert
            mock_request.assert_called_once()
            args, kwargs = mock_request.call_args
            assert kwargs["params"]["jql"] == "status = Open AND assignee = currentUser()"

    def test_search_04_jql_detection_with_or_operator(self):
        """SEARCH-04: JQL detection with OR operator"""
        # Arrange
        with open(self.config_file, 'w') as f:
            yaml.dump(self.valid_config, f)

        mock_response = self.create_mock_jira_response([], total=0)

        with patch('mcp_jira_server.search.make_jira_request') as mock_request:
            mock_request.return_value.status_code = 200
            mock_request.return_value.json.return_value = mock_response

            from mcp_jira_server.config import load_config
            from mcp_jira_server.search import search_issues

            load_config(str(self.config_file))

            # Act
            search_issues("priority = High OR priority = Critical", max_results=25, start_page=0)

            # Assert
            mock_request.assert_called_once()
            args, kwargs = mock_request.call_args
            assert kwargs["params"]["jql"] == "priority = High OR priority = Critical"

    def test_search_05_jql_detection_with_order_by_clause(self):
        """SEARCH-05: JQL detection with "order by" clause"""
        # Arrange
        with open(self.config_file, 'w') as f:
            yaml.dump(self.valid_config, f)

        mock_response = self.create_mock_jira_response([], total=0)

        with patch('mcp_jira_server.search.make_jira_request') as mock_request:
            mock_request.return_value.status_code = 200
            mock_request.return_value.json.return_value = mock_response

            from mcp_jira_server.config import load_config
            from mcp_jira_server.search import search_issues

            load_config(str(self.config_file))

            # Act
            search_issues("project = TEST order by created DESC", max_results=25, start_page=0)

            # Assert
            mock_request.assert_called_once()
            args, kwargs = mock_request.call_args
            assert kwargs["params"]["jql"] == "project = TEST order by created DESC"

    # Pagination Tests (SEARCH-06 to SEARCH-11)

    def test_search_06_return_page_0_with_first_25_issues_default_parameters(self):
        """SEARCH-06: Return page 0 with first 25 issues (default parameters)"""
        # Arrange
        with open(self.config_file, 'w') as f:
            yaml.dump(self.valid_config, f)

        # Create 25 mock issues
        mock_issues = [
            self.create_mock_issue_data(f"TEST-{i}", f"Issue {i}")
            for i in range(1, 26)
        ]
        mock_response = self.create_mock_jira_response(mock_issues, total=50)  # More total than current page

        with patch('mcp_jira_server.search.make_jira_request') as mock_request:
            mock_request.return_value.status_code = 200
            mock_request.return_value.json.return_value = mock_response

            from mcp_jira_server.config import load_config
            from mcp_jira_server.search import search_issues

            load_config(str(self.config_file))

            # Act - use default parameters
            result = search_issues("project = TEST")

            # Assert
            assert isinstance(result, PagedResult)
            assert len(result.items) == 25
            assert result.total_count == 50
            assert result.current_page == 0
            assert result.page_size == 25
            assert result.has_more is True

            # Verify API call parameters
            mock_request.assert_called_once()
            args, kwargs = mock_request.call_args
            assert kwargs["params"]["maxResults"] == 25
            assert kwargs["params"]["startAt"] == 0

    def test_search_07_return_page_1_with_next_5_issues(self):
        """SEARCH-07: Return page 1 with next 5 issues"""
        # Arrange
        with open(self.config_file, 'w') as f:
            yaml.dump(self.valid_config, f)

        # Create 5 mock issues for page 1
        mock_issues = [
            self.create_mock_issue_data(f"TEST-{i}", f"Issue {i}")
            for i in range(6, 11)  # Issues 6-10 (page 1 with max_results=5)
        ]
        mock_response = self.create_mock_jira_response(mock_issues, total=30)
        mock_response["startAt"] = 5  # Starting at item 5 (page 1)

        with patch('mcp_jira_server.search.make_jira_request') as mock_request:
            mock_request.return_value.status_code = 200
            mock_request.return_value.json.return_value = mock_response

            from mcp_jira_server.config import load_config
            from mcp_jira_server.search import search_issues

            load_config(str(self.config_file))

            # Act
            result = search_issues("project = TEST", max_results=5, start_page=1)

            # Assert
            assert isinstance(result, PagedResult)
            assert len(result.items) == 5
            assert result.total_count == 30
            assert result.current_page == 1
            assert result.page_size == 5
            assert result.has_more is True  # More pages available (startAt=5, len=5, 5+5=10 < 30)

            # Verify API call parameters for page 1
            mock_request.assert_called_once()
            args, kwargs = mock_request.call_args
            assert kwargs["params"]["maxResults"] == 5
            assert kwargs["params"]["startAt"] == 5  # page 1 * page_size 5

    def test_search_08_has_more_true_when_more_pages_available(self):
        """SEARCH-08: has_more: true when more pages available"""
        # Arrange
        with open(self.config_file, 'w') as f:
            yaml.dump(self.valid_config, f)

        mock_issues = [
            self.create_mock_issue_data(f"TEST-{i}", f"Issue {i}")
            for i in range(1, 11)  # 10 issues
        ]
        mock_response = self.create_mock_jira_response(mock_issues, total=100)  # Much more total

        with patch('mcp_jira_server.search.make_jira_request') as mock_request:
            mock_request.return_value.status_code = 200
            mock_request.return_value.json.return_value = mock_response

            from mcp_jira_server.config import load_config
            from mcp_jira_server.search import search_issues

            load_config(str(self.config_file))

            # Act
            result = search_issues("project = TEST", max_results=10, start_page=0)

            # Assert
            assert result.has_more is True
            assert result.total_count == 100
            assert len(result.items) == 10

    def test_search_09_current_page_matches_requested_start_page(self):
        """SEARCH-09: current_page matches requested start_page"""
        # Arrange
        with open(self.config_file, 'w') as f:
            yaml.dump(self.valid_config, f)

        mock_response = self.create_mock_jira_response([], total=0)

        with patch('mcp_jira_server.search.make_jira_request') as mock_request:
            mock_request.return_value.status_code = 200
            mock_request.return_value.json.return_value = mock_response

            from mcp_jira_server.config import load_config
            from mcp_jira_server.search import search_issues

            load_config(str(self.config_file))

            # Test multiple start_page values
            for start_page in [0, 1, 2, 5]:
                with self.subTest(start_page=start_page):
                    # Act
                    result = search_issues("project = TEST", max_results=10, start_page=start_page)

                    # Assert
                    assert result.current_page == start_page

    def test_search_10_total_count_accurately_reflects_total_matching_issues(self):
        """SEARCH-10: total_count accurately reflects total matching issues"""
        # Arrange
        with open(self.config_file, 'w') as f:
            yaml.dump(self.valid_config, f)

        test_cases = [
            (0, 0),     # No results
            (5, 5),     # Few results
            (100, 100),  # Many results
            (1000, 1000)  # Large result set
        ]

        with patch('mcp_jira_server.search.make_jira_request') as mock_request:
            from mcp_jira_server.config import load_config
            from mcp_jira_server.search import search_issues

            load_config(str(self.config_file))

            for returned_count, total_count in test_cases:
                with self.subTest(total=total_count):
                    # Create appropriate number of mock issues (up to 25 for current page)
                    issues_in_page = min(returned_count, 25)
                    mock_issues = [
                        self.create_mock_issue_data(f"TEST-{i}", f"Issue {i}")
                        for i in range(1, issues_in_page + 1)
                    ]
                    mock_response = self.create_mock_jira_response(mock_issues, total=total_count)

                    mock_request.return_value.status_code = 200
                    mock_request.return_value.json.return_value = mock_response
                    mock_request.reset_mock()

                    # Act
                    result = search_issues("project = TEST", max_results=25, start_page=0)

                    # Assert
                    assert result.total_count == total_count

    def test_search_11_empty_result_with_total_count_0_and_has_more_false(self):
        """SEARCH-11: Empty result with total_count: 0 and has_more: false"""
        # Arrange
        with open(self.config_file, 'w') as f:
            yaml.dump(self.valid_config, f)

        mock_response = self.create_mock_jira_response([], total=0)

        with patch('mcp_jira_server.search.make_jira_request') as mock_request:
            mock_request.return_value.status_code = 200
            mock_request.return_value.json.return_value = mock_response

            from mcp_jira_server.config import load_config
            from mcp_jira_server.search import search_issues

            load_config(str(self.config_file))

            # Act
            result = search_issues("project = NONEXISTENT", max_results=25, start_page=0)

            # Assert
            assert isinstance(result, PagedResult)
            assert len(result.items) == 0
            assert result.total_count == 0
            assert result.has_more is False
            assert result.current_page == 0
            assert result.page_size == 25

    # Error Handling Tests (SEARCH-12 to SEARCH-14)

    def test_search_12_fail_with_specific_syntax_error_for_invalid_jql(self):
        """SEARCH-12: Fail with specific syntax error for invalid JQL"""
        # Arrange
        with open(self.config_file, 'w') as f:
            yaml.dump(self.valid_config, f)

        # Mock JIRA API returning 400 Bad Request for invalid JQL
        with patch('mcp_jira_server.search.make_jira_request') as mock_request:
            mock_request.return_value.status_code = 400
            mock_request.return_value.json.return_value = {
                "errorMessages": ["JQL query is invalid"],
                "errors": {
                    "jql": "Error in the JQL Query: Expecting text but got end of query."
                }
            }

            from mcp_jira_server.config import load_config
            from mcp_jira_server.search import search_issues, JQLSyntaxError

            load_config(str(self.config_file))

            # Act & Assert
            with pytest.raises(JQLSyntaxError, match="JQL query is invalid"):
                search_issues("invalid jql = syntax AND", max_results=25, start_page=0)

    def test_search_13_fail_with_authentication_error(self):
        """SEARCH-13: Fail with authentication error"""
        # Arrange
        with open(self.config_file, 'w') as f:
            yaml.dump(self.valid_config, f)

        # Mock JIRA API returning 401 Unauthorized
        with patch('mcp_jira_server.search.make_jira_request') as mock_request:
            mock_request.return_value.status_code = 401
            mock_request.return_value.json.return_value = {
                "errorMessages": ["You are not authenticated."],
                "errors": {}
            }

            from mcp_jira_server.config import load_config
            from mcp_jira_server.search import search_issues
            from mcp_jira_server.config import AuthenticationError

            load_config(str(self.config_file))

            # Act & Assert
            with pytest.raises(AuthenticationError, match="You are not authenticated"):
                search_issues("project = TEST", max_results=25, start_page=0)

    def test_search_14_fail_with_timeout_error_for_network_timeout(self):
        """SEARCH-14: Fail with timeout error for network timeout"""
        # Arrange
        with open(self.config_file, 'w') as f:
            yaml.dump(self.valid_config, f)

        # Mock network timeout
        with patch('mcp_jira_server.search.make_jira_request') as mock_request:
            from requests.exceptions import Timeout
            mock_request.side_effect = Timeout("Request timed out")

            from mcp_jira_server.config import load_config
            from mcp_jira_server.search import search_issues, SearchTimeoutError

            load_config(str(self.config_file))

            # Act & Assert
            with pytest.raises(SearchTimeoutError, match="Request timed out"):
                search_issues("project = TEST", max_results=25, start_page=0)

    def test_search_15_field_selection_explicit_fields_only(self):
        """SEARCH-15: Field selection returns only specified fields"""
        # Arrange
        with open(self.config_file, 'w') as f:
            yaml.dump(self.valid_config, f)

        mock_issues = [
            self.create_mock_issue_data("TEST-123", "Test issue")
        ]
        mock_response = self.create_mock_jira_response(mock_issues, total=1)

        with patch('mcp_jira_server.search.make_jira_request') as mock_request:
            mock_request.return_value.status_code = 200
            mock_request.return_value.json.return_value = mock_response

            from mcp_jira_server.config import load_config
            from mcp_jira_server.search import search_issues

            load_config(str(self.config_file))

            # Act
            search_issues("project = TEST", fields="key,summary,status")
            
            # Assert
            mock_request.assert_called_once()
            args, kwargs = mock_request.call_args
            assert kwargs["params"]["fields"] == "key,summary,status"


if __name__ == "__main__":
    unittest.main()