#!/usr/bin/env python3
"""Common Test Data and Utilities for MCP JIRA Server Tests

Generated By: Cursor (Claude Sonnet 4)

Shared test fixtures, sample data, and utilities used across multiple test files.
Contains realistic JIRA API response data based on real responses from issues.redhat.com.
"""

from typing import Dict, List, Any

# Sample JIRA API response structures for testing (anonymized data with realistic structure)
SAMPLE_JIRA_ISSUE_RESPONSE: Dict[str, Any] = {
    "expand": "renderedFields,names,schema,operations,editmeta,changelog,versionedRepresentations",
    "id": "12345678",
    "self": "https://jira.example.com/rest/api/2/issue/12345678",
    "key": "PROJ-123",
    "fields": {
        "summary": "Implement automated notification system for workflow events",
        "issuetype": {
            "self": "https://jira.example.com/rest/api/2/issuetype/2",
            "id": "2",
            "description": "Feature requests from customers and/or users",
            "iconUrl": "https://jira.example.com/secure/viewavatar?size=xsmall&avatarId=13271&avatarType=issuetype",
            "name": "Feature Request",
            "subtask": False,
            "avatarId": 13271
        },
        "status": {
            "self": "https://jira.example.com/rest/api/2/status/6",
            "description": "The issue is closed. See the resolution for context regarding why (for example Done, Abandoned, Duplicate, etc)",
            "iconUrl": "https://jira.example.com/images/icons/statuses/closed.png",
            "name": "Closed",
            "id": "6",
            "statusCategory": {
                "self": "https://jira.example.com/rest/api/2/statuscategory/3",
                "id": 3,
                "key": "done",
                "colorName": "success",
                "name": "Done"
            }
        },
        "resolution": {
            "self": "https://jira.example.com/rest/api/2/resolution/1",
            "id": "1",
            "description": "This issue is closed, and complete.",
            "name": "Done"
        },
        "priority": {
            "self": "https://jira.example.com/rest/api/2/priority/3",
            "iconUrl": "https://jira.example.com/images/icons/priorities/medium.svg",
            "name": "Medium",
            "id": "3"
        },
        "assignee": {
            "self": "https://jira.example.com/rest/api/2/user?username=john.doe",
            "name": "john.doe@example.com",
            "key": "JIRAUSER123456",
            "displayName": "John Doe",
            "active": True,
            "timeZone": "America/New_York"
        },
        "reporter": {
            "self": "https://jira.example.com/rest/api/2/user?username=jane.smith",
            "name": "jane.smith@example.com",
            "key": "JIRAUSER789012",
            "displayName": "Jane Smith",
            "active": True,
            "timeZone": "Europe/London"
        },
        "created": "2024-01-15T10:30:00.000+0000",
        "updated": "2024-01-20T14:45:00.000+0000",
        "resolutiondate": "2024-01-20T16:30:00.000+0000",
        "description": "This feature request aims to enhance the system's automation capabilities by implementing a comprehensive notification framework that triggers alerts when specific workflow events occur. The system should support multiple notification channels and customizable message templates.",
        "project": {
            "self": "https://jira.example.com/rest/api/2/project/10001",
            "id": "10001",
            "key": "PROJ",
            "name": "Sample Project",
            "projectTypeKey": "software"
        },
        "components": [
            {
                "self": "https://jira.example.com/rest/api/2/component/20001",
                "id": "20001",
                "name": "Notifications"
            },
            {
                "self": "https://jira.example.com/rest/api/2/component/20002",
                "id": "20002",
                "name": "Automation"
            }
        ],
        "labels": ["automation", "notifications"],
        "customfield_10001": None,  # Epic Link
        "customfield_10002": None,  # Parent Link
        "subtasks": [],
        "issuelinks": []
    }
}

SAMPLE_JIRA_SEARCH_RESPONSE: Dict[str, Any] = {
    "expand": "names,schema",
    "startAt": 0,
    "maxResults": 25,
    "total": 1,
    "issues": [SAMPLE_JIRA_ISSUE_RESPONSE]
}

SAMPLE_FIELD_METADATA_RESPONSE: List[Dict[str, Any]] = [
    {
        "id": "customfield_10001",
        "name": "Epic Link",
        "custom": True,
        "orderable": True,
        "navigable": True,
        "searchable": True,
        "clauseNames": ["cf[10001]", "Epic Link"],
        "schema": {
            "type": "any",
            "custom": "com.pyxis.greenhopper.jira:gh-epic-link",
            "customId": 10001
        }
    },
    {
        "id": "customfield_10002", 
        "name": "Parent Link",
        "custom": True,
        "orderable": True,
        "navigable": True,
        "searchable": True,
        "clauseNames": ["cf[10002]", "Parent Link"],
        "schema": {
            "type": "issuelink",
            "custom": "com.atlassian.jira.plugin.system.customfieldtypes:issuelinks",
            "customId": 10002
        }
    }
]

# Sample configuration data for tests
SAMPLE_VALID_CONFIG: Dict[str, Any] = {
    "jira": {
        "base_url": "https://jira.example.com",
        "authentication": {
            "type": "bearer_token",
            "token": "${JIRA_TOKEN}"
        },
        "field_metadata_cache": {
            "projects": [
                {"project_key": "PROJ", "sample_issue": "PROJ-123"},
                {"project_key": "TEST", "sample_issue": "TEST-456"}
            ]
        },
        "api": {
            "timeout_seconds": 30,
            "max_retries": 3,
            "retry_delay_seconds": 1
        }
    }
}

# Additional sample issues for testing different scenarios
SAMPLE_JIRA_STORY_RESPONSE: Dict[str, Any] = {
    "expand": "renderedFields,names,schema,operations,editmeta,changelog,versionedRepresentations",
    "id": "87654321",
    "self": "https://jira.example.com/rest/api/2/issue/87654321",
    "key": "PROJ-456",
    "fields": {
        "summary": "Create dashboard widget for real-time data visualization",
        "issuetype": {
            "self": "https://jira.example.com/rest/api/2/issuetype/3",
            "id": "3",
            "description": "A user story",
            "iconUrl": "https://jira.example.com/images/icons/issuetypes/story.svg",
            "name": "Story",
            "subtask": False
        },
        "status": {
            "self": "https://jira.example.com/rest/api/2/status/3",
            "description": "This issue is being actively worked on",
            "iconUrl": "https://jira.example.com/images/icons/statuses/inprogress.png",
            "name": "In Progress",
            "id": "3"
        },
        "priority": {
            "self": "https://jira.example.com/rest/api/2/priority/2",
            "iconUrl": "https://jira.example.com/images/icons/priorities/high.svg",
            "name": "High",
            "id": "2"
        },
        "assignee": {
            "self": "https://jira.example.com/rest/api/2/user?username=dev.team",
            "name": "dev.team@example.com",
            "displayName": "Development Team",
            "active": True
        },
        "created": "2024-02-01T09:15:00.000+0000",
        "updated": "2024-02-05T16:20:00.000+0000",
        "description": "As a business analyst, I want to view real-time metrics in an interactive dashboard widget so that I can monitor system performance and make data-driven decisions quickly.",
        "customfield_10001": "EPIC-200",  # Epic Link
        "customfield_10002": None,        # Parent Link
        "subtasks": [
            {"id": "11111111", "key": "TASK-789", "self": "https://jira.example.com/rest/api/2/issue/11111111"}
        ]
    }
}

def create_mock_jira_response(status_code: int = 200, data: Any = None, error_messages: List[str] = None):
    """Create a mock HTTP response for JIRA API calls"""
    from unittest.mock import Mock
    
    mock_response = Mock()
    mock_response.status_code = status_code
    
    if status_code == 200:
        mock_response.json.return_value = data or SAMPLE_JIRA_ISSUE_RESPONSE
    else:
        mock_response.json.return_value = {
            "errorMessages": error_messages or ["An error occurred"]
        }
    
    return mock_response