#!/usr/bin/env python3
# Generated by: Cursor (Claude)
"""
JIRA Extractor - Command-line tool for extracting JIRA issues and related issues

Copyright (C) 2025 Naveen Z. Malik
This program is licensed under GPL-3.0-or-later
"""

from .client import JiraClient
from .cli import main, create_parser, setup_logging, validate_url, write_output

__version__ = "1.0.0"
__all__ = ["JiraClient", "main", "create_parser", "setup_logging", "validate_url", "write_output"]