#!/usr/bin/env python3
# Generated by: Cursor (Claude)
"""
Feature-based test organization for JIRA Extractor

This file provides feature-based access to unit tests.
Tests are organized by functionality rather than implementation files.
"""

# Feature-based test organization
# Tests can be run by feature using: python -m unittest test_features_<feature>


class LoggingTests:
    """Tests for LOGGING feature"""
    # LOGGING-01: test_setup_logging_info_level
    # LOGGING-02: test_setup_logging_debug_level  
    # LOGGING-03: test_debug_logging
    pass


class URLTests:
    """Tests for URL feature"""
    # URL-01: test_validate_url_with_scheme
    # URL-02: test_validate_url_without_scheme
    # URL-03: test_validate_url_invalid
    # URL-04: test_init_url_normalization
    pass


class AuthTests:
    """Tests for AUTH feature"""
    # AUTH-01 through AUTH-19: All authentication-related tests
    pass


class OutputTests:
    """Tests for OUTPUT feature"""
    # OUTPUT-01 through OUTPUT-11: All output management tests
    pass


class ParsingTests:
    """Tests for PARSING feature"""
    # PARSING-01 through PARSING-10: All command line parsing tests
    pass


class ExecutionTests:
    """Tests for EXECUTION feature"""
    # EXECUTION-01 through EXECUTION-07: All main execution flow tests
    pass


class DescendantTests:
    """Tests for DESCENDANT feature"""
    # DESCENDANT-01 through DESCENDANT-15: All descendant extraction tests
    pass


class FieldManagementTests:
    """Tests for FIELD-MGMT feature"""
    # FIELD-MGMT-01 through FIELD-MGMT-10: All field management tests
    pass


class IssueRetrievalTests:
    """Tests for ISSUE-RETRIEVAL feature"""
    # ISSUE-RETRIEVAL-01 through ISSUE-RETRIEVAL-07: All issue retrieval tests
    pass


class RelationshipTests:
    """Tests for RELATIONSHIPS feature"""
    # RELATIONSHIPS-01 through RELATIONSHIPS-06: All relationship processing tests
    pass
